# Generated by Django 5.1.6 on 2025-02-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Task_status',
            field=models.BooleanField(default=False),
        ),
    ]
