# Generated by Django 5.1.6 on 2025-02-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_details_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='task_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
