# Generated by Django 5.1.6 on 2025-02-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_details_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Task_status',
            new_name='task_status',
        ),
    ]
